language: scala
jdk: oraclejdk8
scala:
  - 2.12.1
java:
  -

script:
  - sbt test
  - sbt assembly

#before_deploy:
#  - zip -r deploy.zip target/scala-2.12/content-camera-service.jar Dockerfile

#deploy:
#  provider: elasticbeanstalk
#  skip_cleanup: true
#  app: Portal
#  env: dev-smartcart-portal
#  bucket_name: elasticbeanstalk-us-east-1-754825644043
#  zip_file: deploy.zip
#  region: us-east-1
#  access_key_id: AKIAJODYYJKAW5FWQKKA
#  secret_access_key:
#    secure: oT60iv23E2mR0pNYC1Vsum3KHDKHDhLy1vARnAbJPKk/JMBJrxJ6W7kqXf1oOl4tlWsflG4ucAjOWvWKkR7uutxplRN48Hv6O3yVMZoPcvMF5Y0Q/wd3/ktEkllZlu9PUzcniDRG5K1g2+RTb4Hfz+0FHYprzCakvDvNyroIPGhZc3D9bMu0LJ8mURE8odSBMNsJpBAaMBZqkqiXetEqgg/Qx15ISLD7V3cjgdaAssQ+jFoLveEjC5aDzdrsUub9beXwmitEIdO9ITwCq65Q3enRUCTwyhLMfLFTaB7T75FPG/c2712a6Oe0JP0qGR5RwRT92wknKYKTUY7sDzGw14KKUiiqJoxHxslfrIW3vare9AppYXb/qFaZKN+9B2ouIPCIQL0LPT+O69OK2ggVwAvtIZ5eEj9yCNC5btszqMmtXK21hhf8ByYNyZPHdqYHBBMKny3+iSdvKS6NkhNS5aOFlBygvurnyMzA9rEjnXruk2tofp77weaVrsZetojrnEV7aJ/UHVy4uJw+qxZ42SgQQNGmmWLTBwh2H2WFHPQPNVozv11HMKZOrBioIXAqf4hyaOcdupT/5IGVPgE6L46lms3X1EtwQ9c2nTNJ4iVjAA5PJG/cz56nnfB/s6ahCT4e7G9ByBEXwloTozxbNm+GZ7Zr7uuXL7NrlLx8RkQ=
#  on:
#    branch: master
