language: scala
jdk: oraclejdk8
scala:
  - 2.12.1

script:
  - sbt test
  - sbt assembly

before_deploy:
  - zip -r deploy.zip target/scala-2.12/content-camera-service.jar Dockerfile

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  app: image-grouper
  env: dev-image-grouper
  bucket_name: elasticbeanstalk-us-east-1-484909666141
  zip_file: deploy.zip
  region: us-east-1
  access_key_id: AKIAJVHFB43AE27SYC2A
  secret_access_key:
    secure: "l5nF8JGBj11moHlgXsb7LbI6HKaJ8QahdvP/b4G+5dlF0xBJJB35UpQA4F20inXA7xRCzymwixjoXsq9sZ0i9A+jWhRVOJg40ILaO2mzZ/s/5Ce3XV2XzQAZY2xoiNXGDRrtCWakCo4jMrum2U6L3muIO6Y1jV9l8SU51893gble6dl4k0I2JqzgXuPAVJMTuQO/uYmPcwavwlVdFTUCLg0xe2IxTRQ+hyJl2ArVpD2V7saH4pw97d2vOW8hutKFjtrcAF+ll4YeeZ8KxmqFe739r8MJir806RofWH+weFl2cQrMXAFh4XftTZ+8Bwt+q1U5wVYu+ggpmLKH+X9ySkPLACJ+SEy8dyDjt89/M3WUJOh3A3zIQ8s6Zh3RoqxPxUpSgYNima9N++WgQjVe6izMJzUJdHsYXBl1C8u7JSSJtRghyzcxiNAe1XkQnGLsylFyh8NvUjDK8uncm8v0YxuF+oZJrNhiAf3M3U02Z4UWuw2HNmGOv7RmKQwYJtfHCzRkwu+v9NyxSlreUnXnmAOXqCqbd/DRvMX1HjukftYrkN9+xLcNodH5D8ErrAbDi8IGqhpr8AVuAwBICdU7EaybhdK+LHV5JAcBBy9nC4KOq6hYQaSEG4tKGUcQfXet6fiKWwmlP09oZ6E5rj42L1TJE7Njze0heXXkxBNI/Gc="
  on:
    branch: master
